version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: docker/django/local/Dockerfile
    volumes:
      - .:/home/django/code
    ports:
      - 8000:8000
    command: /start.sh
    depends_on:
      - database
  database:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ssh_application
      POSTGRES_USER: diploma_user
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:

