version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: docker/django/production/Dockerfile
    volumes:
      - .:/home/django/code
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
    command: /start.sh
  database:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ssh_application
      POSTGRES_USER: diploma_user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d ssh_application -U diploma_user' ]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

