version: "3.9"

name: diploma-test
services:
  django:
    build:
      context: .
      dockerfile: docker/django/test/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env.test
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: ssh_application
      POSTGRES_USER: diploma_user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d ssh_application -U diploma_user' ]
      interval: 2s
      timeout: 5s
      retries: 5

