version: "3.9"

name: diploma-test
services:
  django:
    build:
      context: .
      dockerfile: docker/django/test/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env.local
  database:
    image: postgres:15
    env_file:
      - .env.local
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}' ]
      interval: 2s
      timeout: 5s
      retries: 5

