# Generated by Django 4.2.3 on 2023-09-16 12:22

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(null=True, verbose_name=255),
        ),
        migrations.AlterField(
            model_name='keypair',
            name='public_key_content',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
