# Generated by Django 4.2.3 on 2023-08-20 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=40)),
                ('devices', models.ManyToManyField(blank=True, related_name='groups', to='application.device')),
                ('public_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.publickey')),
            ],
        ),
    ]
