# Generated by Django 4.2.3 on 2023-08-22 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key_content', models.TextField(unique=True)),
                ('public_key_content', models.TextField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='device',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='group',
            name='public_key',
        ),
        migrations.DeleteModel(
            name='PublicKey',
        ),
        migrations.AddField(
            model_name='customuser',
            name='key_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.keypair'),
        ),
        migrations.AddField(
            model_name='device',
            name='key_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.keypair'),
        ),
        migrations.AddField(
            model_name='group',
            name='key_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.keypair'),
        ),
    ]
