# Generated by Django 4.2.3 on 2023-11-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_customuser_key_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='public_key',
            field=models.TextField(null=True),
        ),
    ]
