version: "3.9"

services:
  django:
    build: ../docker/django/production
    volumes:
      - .:/home/django/code
    ports:
      - 8000:8000
    depends_on:
      - database
  database:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ssh_application
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:

