name: Deliver image

on:
  release:
    types:
      - released

jobs:
  deliver:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Echo Git Tag
        id: git_tag
        run: echo ${{ github.event.release.tag_name }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ssh-configurator-api:${{ github.event.release.tag_name }} -f docker/django/production/Dockerfile .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ssh-configurator-api:latest -f docker/django/production/Dockerfile .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ssh-configurator-api:${{ github.event.release.tag_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/ssh-configurator-api:latest
