name: Deliver image

on:
  push:
    branches:
      - '*'

jobs:
  deliver:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#      - name: Get Git Tag
#        id: git_tag
#        run: echo "::set-output name=TAG::$(git describe --tags --abbrev=0)"
#
#      - name: Build Docker image with version
#        run: docker build -t ssh-configurator-api:${{ steps.git_tag.outputs.TAG }} -f docker/django/production/Dockerfile .
#
#      - name: Push Docker image with version
#        run: docker push ssh-configurator-api:${{ steps.git_tag.outputs.TAG }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ssh-configurator-api:latest -f docker/django/production/Dockerfile .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ssh-configurator-api:latest
