name: Run unit tests

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build containers and pull images
        run: |
          docker compose -f=test.yml build
          docker compose -f=test.yml pull

      - name: Run tests
        run: docker compose --env-file=.env.local -f=test.yml up --abort-on-container-exit
